stages:
  - lint
  - test

default:
  image: node:22.11.0

.node:
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  before_script:
    - npm ci

code-style:
  extends: .node
  stage: lint
  script:
    - npm run lint:ci

test-api:
  extends: .node
  stage: test
  script:
    - cp $ENV_FILE .env
    - npm test

