stages:
  - lint
  - test
  - report
  - build
  - deploy

default:
  image: node:20.11.0

eslint:
  stage: lint
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run lint:ci

test:
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - cp $ENV_FILE .env
    - npm test
  artifacts:
    paths:
      - reports/allure-results

allure:
  stage: report
  dependencies:
    - test
  image: registry.gitlab.com/freepad/qajs-2023-12/allure:latest
  script:
    - cp -r reports/allure-results /app
    - cd /app
    - npx allure generate allure-results --clean
    - cp -r app/allure-report $CI_PROJECT_DIR
  artifacts:
    paths:
      - allure-report

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

pages:
  stage: deploy
  image: alpine:latest
  dependencies:
    - allure
  script:
    - mkdir -p public
    - cp -r allure-report/* public/
  artifacts:
    paths:
      - public
