stages:
  - lint
  - test

code-style:
  stage: lint
  image: node:20.18.1
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  script:
    - npm ci
    - npm run lint:ci

test-api:
  stage: test
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  image: node:20.18.1
  script:
    - npm ci
    - npm test

