stages:
  - lint
  - test
  - report

default:
  image: node:22.11.0

.node:
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  before_script:
    - npm ci

code-style:
  extends: .node
  stage: lint
  script:
    - npm run lint:ci

test-api:
  extends: .node
  stage: test
  script:
    - cp $ENV_FILE .env
    - npm test
  artifacts:
    when: always
    paths:
      - reports/allure-reports

report:
  dependencies:
    - test-api
  stage: report
  image: registry.gitlab.com/freepad/qajs_2024_12/allure
  script:
    - allure generate reports/allure-results --clean --report-dir reports/allure-report
  artifacts:
    paths:
      - reports/allure-report
